#!/bin/bash
PIDFILE="/tmp/pid"

terminate() {    
    PID=$(cat /tmp/pid)
    kill -1 $PID
    wait $PID
    rm $PIDFILE
    exit 0
}

trap terminate SIGHUP SIGINT SIGQUIT SIGTERM

echo "" > $PIDFILE
groovy server.groovy | tee /var/log/tsa.log&
PID=$!
echo $PID > $PIDFILE

wait $PID

